[options]
addons_path = /mnt/eha-addons/enterprise,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons,/mnt/eha-addons,/mnt/eha-addons/mattobell_eha_clinic,/mnt/eha-addons/eha_clinic
csv_internal_sep = ,
auto_reload = True
data_dir = /var/lib/odoo
db_maxconn = 128
db_port = 5432
; db_template = template1
dbfilter = .*
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
import_partial =
limit_memory_hard = 3084354560
limit_memory_soft = 2684354560
limit_request = 8192
limit_time_cpu = 720
limit_time_real = 720
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo.log
logrotate = False
longpolling_port = 8072
max_cron_threads = 1
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
; server_wide_modules = web,web_kanban
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
; translate_modules = ['all']
unaccent = False
without_demo = False
workers = 4
xmlrpc = True
xmlrpc_interface =
xmlrpc_port = 8069
admin_passwd = $ADMIN_PASSWORD
sentry_dsn = $SENTRY_DSN
sentry_enabled = $SENTRY_ENABLED
